import { UserRole } from '@knowledge-base-central/shared';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.OWNER]: ['*'],
  [UserRole.ADMIN]: [
    'article:view',
    'article:create',
    'article:update',
    'article:delete',
    'article:publish',
    'article:archive',
    'article:restore',
    'concept:view',
    'concept:create',
    'concept:update',
    'concept:delete',
    'category:view',
    'category:create',
    'category:update',
    'category:delete',
    'tag:view',
    'tag:create',
    'tag:update',
    'tag:delete',
    'reference:view',
    'reference:create',
    'reference:update',
    'reference:delete',
    'learning-path:view',
    'learning-path:create',
    'learning-path:update',
    'learning-path:delete',
    'attachment:create',
    'attachment:update',
    'attachment:delete',
    'comment:view',
    'comment:moderate',
    'correction:view',
    'correction:approve',
    'correction:reject',
    'user:view',
    'audit:view',
    'repository:view',
    'repository:sync',
    'search:manage',
  ],
  [UserRole.EDITOR]: [
    'article:view',
    'article:create',
    'article:update',
    'concept:view',
    'concept:create',
    'concept:update',
    'category:view',
    'tag:view',
    'reference:view',
    'reference:create',
    'reference:update',
    'learning-path:view',
    'learning-path:create',
    'learning-path:update',
    'attachment:create',
    'attachment:update',
    'comment:view',
    'correction:view',
  ],
  [UserRole.CONTRIBUTOR]: [
    'article:view',
    'concept:view',
    'category:view',
    'tag:view',
    'reference:view',
    'learning-path:view',
    'comment:view',
    'comment:create',
    'correction:create',
  ],
};

export function roleHasPermission(role: UserRole, permission: string): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  if (permissions.includes('*')) {
    return true;
  }
  return permissions.includes(permission);
}
